---
title: "Exhaustive chart"
author: "Mikkel Meyer Andersen"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Exhaustive chart}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  message = FALSE,
  comment = "#>"
)
```

```{r}
library(dplyr)
library(tidyr)
library(forcats)
library(ggplot2)
library(grid)
library(gridExtra)
library(pichor)
```

```{r}
d_keys_coords <- get_keys_coords()
d_tones <- d_keys_coords %>% 
  filter(key <= 12) %>% 
  rowwise() %>% 
  mutate(tone = tones[1]) %>% 
  select(key, tone, label)
```

```{r}
d_tones_choords <- d_tones %>% 
  rowwise() %>% 
  mutate(
    major = list(construct_chord_major(root_tone = tone)),
    minor = list(construct_chord_minor(root_tone = tone))) %>% 
  gather(type, chord, c(major, minor)) %>% 
  rowwise() %>%
  mutate(root = list(get_keys(chord))) %>% 
  mutate(inversion1 = list(get_keys_inversion(chord = chord, inversion = 1)),
         inversion2 = list(get_keys_inversion(chord = chord, inversion = 2))) %>% 
  select(-chord) %>% 
  gather(variant, keys, c(root, starts_with("inversion"))) %>% 
  mutate(variant = fct_inorder(variant)) %>%
  mutate(tone = fct_inorder(tone)) %>% 
  mutate(caption = paste0(type, " ", label, " (", variant, ")"),
         caption = gsub("\n", "/", caption, fixed = TRUE),
         caption = gsub(" (root)", "", caption, fixed = TRUE)) %>% 
  arrange(tone, type, variant)
d_tones_choords
```

```{r}
figures <- vector("list", nrow(d_tones_choords))

for (i in seq_along(figures)) {
  row <- d_tones_choords %>% slice(i)
  
  p <- d_keys_coords %>% 
    highlight_keys(keys = row %>% pull(keys) %>% unlist()) %>%
    ggpiano(labels = FALSE) +
    labs(title = row %>% pull(caption))
  
  figures[[i]] <- p
}
```

```{r}
nrows <- d_tones_choords %>% distinct(tone, type) %>% nrow()
stopifnot(nrow(d_tones_choords) %% nrows == 0)
ncols <- nrow(d_tones_choords) / nrows
```

```{r, fig.width = 10, fig.height = 20}
do.call(grid.arrange, c(figures, ncol = ncols, nrow = nrows))
```





