---
title: "Introduction"
author: "Mikkel Meyer Andersen"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  message = FALSE,
  fig.width = 8,
  fig.height = 4,
  comment = "#>"
)
```

```{r, message=FALSE}
library(ggplot2)
library(dplyr)
library(pichor)
```

Built-in data with information about some of the keys on a piano:

```{r}
keys_coords
```

Details for drawing a diagram of a piano:


```{r}
ggpiano(keys_coords)
```

Add key labels:

```{r}
ggpiano(keys_coords, labels = TRUE)
```

Highlight certain keys:

```{r}
keys_coords %>% 
  highlight_keys(keys = c(7, 10, 14)) %>%
  ggpiano(labels = TRUE)
```

Work with chords:

```{r}
chrd <- construct_chord_raw(root_tone = "F#", distances_rel = c(4, 3))
chrd
as.character(chrd, brief = TRUE)
chrd_Fsm <- construct_chord_minor(root_tone = "F#")
chrd_Fsm
as.character(chrd_Fsm, brief = TRUE)
get_keys(chord = chrd_Fsm)
get_keys_highest_tone(chord = chrd_Fsm, highest_tone = "A")
```

Highlight chords:

```{r}
keys_coords %>% 
  highlight_chord(chord = chrd_Fsm) %>%  # root form by default
  ggpiano()
keys_coords %>% 
  highlight_chord(chord = chrd_Fsm, highest_tone = "A") %>% 
  ggpiano()
```

Work with chord inversions:

```{r}
chrd_Bm <- construct_chord_minor(root_tone = "B")
get_keys(chord = chrd_Bm)
get_keys_inversion(chord = chrd_Bm, inversion = 0)
get_keys_inversion(chord = chrd_Bm, inversion = 1)
get_keys_inversion(chord = chrd_Bm, inversion = 2)
```


Highlight chord inversions:

```{r}
keys_coords %>% 
  highlight_chord(chord = chrd_Bm, inversion = 0L) %>% 
  ggpiano()
keys_coords %>% 
  highlight_chord(chord = chrd_Bm, inversion = 1L) %>% 
  ggpiano()
keys_coords %>% 
  highlight_chord(chord = chrd_Bm, inversion = 2L) %>% 
  ggpiano()
```



