context("Chords")

test_that("get_key()", {
  expect_error(get_key(""))
  expect_error(get_key("X"))
  expect_error(get_key("?"))
  expect_error(get_key("CD"))
  expect_error(get_key("CB"))
  
  expect_equal(get_key("C"), 1)
  expect_equal(get_key("C#"), 2)
  expect_equal(get_key("Db"), 2)
  expect_equal(get_key("D"), 3)
  expect_equal(get_key("D#"), 4)
  expect_equal(get_key("Eb"), 4)
  expect_equal(get_key("E"), 5)
  expect_equal(get_key("F"), 6)
  expect_equal(get_key("F#"), 7)
  expect_equal(get_key("Gb"), 7)
  expect_equal(get_key("G"), 8)
  expect_equal(get_key("G#"), 9)
  expect_equal(get_key("Ab"), 9)
  expect_equal(get_key("A"), 10)
  expect_equal(get_key("A#"), 11)
  expect_equal(get_key("Bb"), 11)
  expect_equal(get_key("B"), 12)
})

test_that("get_next_key()", {
  expect_equal(get_next_key(origin = 1, distance = 0), 1)
  expect_equal(get_next_key(origin = 1, distance = 3), 4)
  expect_equal(get_next_key(origin = 3, distance = 3), 6)
  expect_equal(get_next_key(origin = 11, distance = 1), 12)
  expect_equal(get_next_key(origin = 11, distance = 2), 1)
  expect_equal(get_next_key(origin = 11, distance = 3), 2)
})

test_that("get_key_color()", {
  expect_equal(get_key_color(1), "white")
  expect_equal(get_key_color(2), "black")
  expect_equal(get_key_color(3), "white")
  expect_equal(get_key_color(4), "black")
  expect_equal(get_key_color(5), "white")
  expect_equal(get_key_color(6), "white")
  expect_equal(get_key_color(7), "black")
  expect_equal(get_key_color(8), "white")
  expect_equal(get_key_color(9), "black")
  expect_equal(get_key_color(10), "white")
  expect_equal(get_key_color(11), "black")
  expect_equal(get_key_color(12), "white")
})
